"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar } from "recharts";
import { Activity, Brain, HeartPulse, FileText, CheckCircle, AlertTriangle } from "lucide-react";

export default function PatientReport() {
  const router = useRouter();
  const [report, setReport] = useState<any>(null);

  useEffect(() => {
    const raw = localStorage.getItem("kinetiCare_latestReport");
    if (raw) setReport(JSON.parse(raw));
  }, []);

  if (!report) return (
    <div className="min-h-screen bg-slate-950 flex items-center justify-center text-teal-400">
      Loading Supreme Dashboard...
    </div>
  );

  const { models } = report;

  // Mock historical crossover data for the "Crazy" Chart
  const stressCrossoverData = [
    { day: "Mon", HR: 72, tremor: 0.15, depRisk: 0.2 },
    { day: "Tue", HR: 75, tremor: 0.18, depRisk: 0.25 },
    { day: "Wed", HR: 88, tremor: 0.45, depRisk: 0.6 },
    { day: "Thu", HR: 82, tremor: 0.35, depRisk: 0.5 },
    { day: "Today", HR: models.ppg.heart_rate, tremor: models.kineticare.neurological_risk_index * 100, depRisk: models.depression.risk_score * 100 },
  ];

  const radarData = [
    { subject: 'Vitals Stability', A: models.ppg.is_valid ? 90 : 40, fullMark: 100 },
    { subject: 'Motor Control', A: 100 - (models.kineticare.neurological_risk_index * 100), fullMark: 100 },
    { subject: 'Emotional', A: 100 - (models.depression.risk_score * 100), fullMark: 100 },
    { subject: 'Cognitive', A: models.kineticare.fatigue_level === "High" ? 40 : 85, fullMark: 100 },
    { subject: 'Cardio Pressure', A: models.ppg.map > 70 && models.ppg.map < 100 ? 95 : 60, fullMark: 100 },
  ];

  const getRiskColor = (score: number) => {
    if (score < 0.4) return "text-teal-400";
    if (score < 0.7) return "text-amber-400";
    return "text-rose-500";
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 p-8 font-sans">
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* Header Ribbon */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-xl">
          <div>
            <h1 className="text-3xl font-bold bg-gradient-to-r from-teal-400 to-blue-500 bg-clip-text text-transparent">
              Comprehensive Clinical Certificate
            </h1>
            <p className="text-slate-400 mt-1">Generated by HuatuoGPT-o1 Master Orchestrator | {new Date(report.timestamp).toLocaleString()}</p>
          </div>
          <button onClick={() => router.push("/")} className="mt-4 md:mt-0 px-6 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-sm font-medium transition-colors border border-slate-700">
            Exit Portal
          </button>
        </div>

        {/* Master AI Summary */}
        <div className="bg-gradient-to-br from-blue-900/40 to-slate-900 border border-blue-800/50 p-6 rounded-2xl shadow-2xl">
          <div className="flex items-center gap-3 mb-4 text-blue-400">
            <CheckCircle className="w-8 h-8" />
            <h2 className="text-xl font-bold">Orchestrator Level-3 Synthesis</h2>
          </div>
          <p className="text-lg leading-relaxed text-slate-300">
            {models.orchestrator.analysis}
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Left Column: Specific Pillars */}
          <div className="space-y-6">
            
            {/* rPPG Vitals */}
            <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-lg relative overflow-hidden">
              <div className="absolute top-0 right-0 p-4 opacity-10"><HeartPulse className="w-24 h-24" /></div>
              <h3 className="text-rose-400 font-bold flex items-center gap-2 mb-4"><HeartPulse className="w-5 h-5"/> Hemodynamics</h3>
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
                  <div className="text-sm text-slate-400">Heart Rate</div>
                  <div className="text-2xl font-mono text-rose-100">{models.ppg.heart_rate} <span className="text-xs text-rose-400">BPM</span></div>
                </div>
                <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
                  <div className="text-sm text-slate-400">Blood Pressure</div>
                  <div className="text-xl font-mono text-rose-100">{models.ppg.sbp}/{models.ppg.dbp}</div>
                </div>
                <div className="col-span-2 bg-slate-950 p-4 rounded-xl border border-slate-800 flex justify-between">
                  <div className="text-sm text-slate-400">Mean Arterial Pressure (MAP)</div>
                  <div className="font-mono text-rose-100">{models.ppg.map} mmHg</div>
                </div>
              </div>
            </div>

            {/* Depression Metric */}
            <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-lg relative overflow-hidden">
              <div className="absolute top-0 right-0 p-4 opacity-10"><Brain className="w-24 h-24" /></div>
              <h3 className="text-purple-400 font-bold flex items-center gap-2 mb-4"><Brain className="w-5 h-5"/> Emotional Phenotype</h3>
              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 flex items-center justify-between mb-4">
                <div className="text-sm text-slate-400">Risk Severity</div>
                <div className={\`text-2xl font-mono \${getRiskColor(models.depression.risk_score)}\`}>
                  {(models.depression.risk_score * 100).toFixed(1)}%
                </div>
              </div>
              <div className="text-xs text-slate-500">
                Confidence: <span className="text-slate-300">{(models.depression.confidence * 100).toFixed(1)}%</span>
              </div>
            </div>

            {/* KinetiCare IMU */}
            <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-lg relative overflow-hidden">
              <div className="absolute top-0 right-0 p-4 opacity-10"><Activity className="w-24 h-24" /></div>
              <h3 className="text-amber-400 font-bold flex items-center gap-2 mb-4"><Activity className="w-5 h-5"/> Neuromotor Tracking</h3>
              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 mb-2">
                <div className="text-sm text-slate-400">Cognitive Fatigue</div>
                <div className="text-xl font-bold text-amber-100">{models.kineticare.fatigue_level}</div>
              </div>
              <div className="text-xs text-slate-500 flex items-center gap-2 pt-2">
                <AlertTriangle className="w-4 h-4 text-amber-500/50" />
                Tremor / Keystroke Lag Index: {(models.kineticare.neurological_risk_index).toFixed(2)}
              </div>
            </div>

          </div>

          {/* Right Column: Supreme Charts */}
          <div className="lg:col-span-2 space-y-6">
            
            {/* Crossover Graph */}
            <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-lg h-[400px] flex flex-col">
              <h3 className="text-xl font-bold text-slate-200 mb-4">Supreme Multi-modal Crossover Analysis</h3>
              <p className="text-sm text-slate-400 mb-6">Visualizing the real-time intersection between elevated Heart Rate (Physiological) and Motor Tremor Delay (Neurological).</p>
              <div className="flex-1 w-full min-h-0">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={stressCrossoverData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                    <XAxis dataKey="day" stroke="#475569" />
                    <YAxis yAxisId="left" stroke="#f43f5e" />
                    <YAxis yAxisId="right" orientation="right" stroke="#f59e0b" />
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', color: '#e2e8f0' }} />
                    <Line yAxisId="left" type="monotone" dataKey="HR" stroke="#f43f5e" strokeWidth={3} dot={{r:6}} name="Heart Rate (BPM)" />
                    <Line yAxisId="right" type="monotone" dataKey="tremor" stroke="#f59e0b" strokeWidth={3} dot={{r:6}} name="Tremor Intensity" />
                    <Line yAxisId="right" type="monotone" dataKey="depRisk" stroke="#a855f7" strokeWidth={3} strokeDasharray="5 5" name="Depression Risk" />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Radar Bio-Profile */}
            <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-lg h-[350px] flex">
              <div className="flex-1">
                <h3 className="text-lg font-bold text-slate-200 mb-2">Holistic Patient Bio-Profile</h3>
                <p className="text-sm text-slate-400">128-dimensional mapping condensed into structural quadrant health.</p>
              </div>
              <div className="flex-[2] h-full">
                <ResponsiveContainer width="100%" height="100%">
                  <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                    <PolarGrid stroke="#1e293b" />
                    <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 12 }} />
                    <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                    <Radar name="Patient Health" dataKey="A" stroke="#14b8a6" fill="#14b8a6" fillOpacity={0.4} strokeWidth={2} />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}
